name: Build and publish static site using nodejs

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget

      - name: Downlaod claat
        run: |
          wget https://github.com/googlecodelabs/tools/releases/download/v2.2.6/claat-linux-amd64
          chmod +x claat-linux-amd64
          sudo mv claat-linux-amd64 /bin/claat
      - name: Compile using claat
        run: ls *.md | xargs claat export

      - name: Use Node.js 12.x
        uses: actions/setup-node@v3
        with:
          node-version: 12.x
      - name: Install dependencies
        run: |
          npm install
          npm install -g gulp-cli
        working-directory: ./site
      - name: Build
        run: |
          gulp dist --codelabs-dir=codelabs
        working-directory: ./site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./site/dist

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
